server:
  port: 11111
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ex-wife?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: dev
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  appId: wx1d39ad72217510a7
  secret: 64eabaa447707a0f169984249b101aa3
security:
  enabled: false